functionsDirectory = "/Users/yamai/ai-101/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
plugins = []
redirects = []

[build]
publish = "/Users/yamai/ai-101"
publishOrigin = "default"
functions = "/Users/yamai/ai-101/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[headers]]
for = "/*"

[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"